server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ikprojedb
    username: postgres
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  mail:
    host: localhost
    port: 25
    username: ''
    password: ''
    protocol: smtp
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

cloudinary:
  cloud_name: dxtmlp6jw
  api_key: 529484785928648
  api_secret: spD9pBPUlI4lTJtbzGr6Is-MGVo